name: cicd

on:
  push:
    branches:
      - master

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    container:
      image: docker:stable
    env:
      DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.DOCKER_KEY_PASSPHRASE }}
      VERSION: cicd
    steps:
        - uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Prepare docker content trust
          run: mkdir -p ~/.docker/trust/private && echo "${{ secrets.DOCKER_KEY }}" > ~/.docker/trust/private/${{ secrets.DOCKER_KEY_NAME }}
        - name: Build image
          run: docker build -t phbelitz/image:$VERSION -f docker/Dockerfile .
        - name: Push image
          run: DOCKER_CONTENT_TRUST=1 docker push phbelitz/image:$VERSION